
- name: download apt keys
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/foo.conf

    
- name: install packages needed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common

- name: install docker
  apt:
   name: docker.io
   state: present
- name: start and enable docker services
  service:
    name: "docker"
    state: started
    enabled: yes

